### ISSUE TITLE
I want know how to use the redis sentinel function?

### ISSUE THREAD

**Issue by yuansetiankong** [ran-jit/TomcatClusterRedisSessionManager#68]
Tomcat log report this issues: I already have three sentinel servers, and enable redis.sentinel.enabled=true:
	org.apache.catalina.LifecycleException: Failed to start component [tomcat.request.session.redis.SessionManager[/examples]]
		at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:198)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5249)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:753)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:727)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:695)
		at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1177)
		at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1925)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)
	Caused by: redis.clients.jedis.exceptions.JedisConnectionException: All sentinels down, cannot determine where is mymaster master is running...
		at redis.clients.jedis.JedisSentinelPool.initSentinels(JedisSentinelPool.java:184)
		at redis.clients.jedis.JedisSentinelPool.<init>(JedisSentinelPool.java:96)
		at redis.clients.jedis.JedisSentinelPool.<init>(JedisSentinelPool.java:83)
		at redis.clients.jedis.JedisSentinelPool.<init>(JedisSentinelPool.java:71)
		at tomcat.request.session.data.cache.impl.redis.RedisSentinelManager.<init>(RedisSentinelManager.java:19)
		at tomcat.request.session.data.cache.impl.redis.RedisCache.initialize(RedisCache.java:71)
		at tomcat.request.session.data.cache.impl.redis.RedisCache.<init>(RedisCache.java:21)
		at tomcat.request.session.data.cache.DataCacheFactory.getDataCache(DataCacheFactory.java:23)
		at tomcat.request.session.redis.SessionManager.initialize(SessionManager.java:215)
		at tomcat.request.session.redis.SessionManager.startInternal(SessionManager.java:87)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)

**Comment by yuansetiankong** [comment]
about version 4.0
